### ISSUE TITLE
Improve collections handling

### ISSUE THREAD

**Issue by dpisarewski** [janfoeh/apidiesel#3]
At the moment, ApiDiesel returns nil if a collection is empty. For example:

action.rb

``` ruby
array :contracts, at: [:contracts, :contract] do
end
```

response.xml

```
<contracts/>
```

I would expect the `contracts` parameter to be an empty array.

**Comment by janfoeh** [comment]
That makes sense to me, too. I'm still on the fence whether to distinguish between "response key is blank" and "response key is missing completely" - return empty array for `<contracts />`, but `nil` when the key is entirely absent.

What do you think?

**Comment by dpisarewski** [comment]
That sounds good

**Comment by janfoeh** [comment]
I'm going to go ahead and assume this no longer is an issue ;)

If it is — `v2` is about to be released and is pretty much a complete rewrite.
